version: 2.1

jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Run Build
          command: make build
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: make testacc
  release:
    docker:
      - image: cimg/go:1.20.5
    steps:
      - checkout
      - run: go install github.com/goreleaser/goreleaser@v1.1.0
      - run: goreleaser release --skip-sign 

workflows:
  build: 
    jobs:
      - build-and-test
  release:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
