version: 2.1

jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Run Build
          command: make build
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      # - run:
      #     name: Run tests
      #     command: |
      #       mkdir -p /tmp/test-reports
      #       gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      # - store_test_results:
      #     path: /tmp/test-reports
  release:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
      - run: goreleaser release --skip-sign 

workflows:
  pr: 
    jobs:
      - build-and-test
  release:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
